on: [push]

jobs:
    build:
        name: Linux

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-16.04, ubuntu-18.04]

        steps:
            - name: Test
              run: echo 'This is only a test !'
              id: test
