on: [push, pull_request]

jobs:
    build:
        name: Linux

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-16.04, ubuntu-18.04] #, windows-latest]

        steps:
            - name: Test
              run: echo 'This is only a test !'
              id: test
            - name: Time test
              run: ls -al ../openstego
#              run: ./compile
